# Generated by Django 5.0.6 on 2025-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_video_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
