# Generated by Django 5.0.6 on 2025-05-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='featured_artists',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='dashboards.artist'),
        ),
    ]
