# Generated by Django 5.0.6 on 2025-05-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_remove_song_featured_artists_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_sale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='debut_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
